fixing deploy.sh

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,10 +41,19 @@ jobs:
           name: deploy-application
           command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
                     
-                    which git || sudo yum update -y && sudo yum install -y git
+                    if ! command -v git &> /dev/null; then
+                      echo 'Git is not found.Install git'
+                      sudo yum update -y 
+                      sudo yum install -y git
+                    fi
+
+                    echo "removing old application directory"
                     rm -rf SimpleApplication_DevOps_CA/
+
+                    echo "cloning repository"
                     git clone https://github.com/SanRob1325/SimpleApplication_DevOps_CA.git
 
+                    echo "Setting up execution by granting permissions"
                     chmod +x SimpleApplication_DevOps_CA/deploy.sh
 
                     bash SimpleApplication_DevOps_CA/deploy.sh
